/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "surface": "#fff9e6",
        "on-primary-container": "#696200",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "surface-variant": "#e8e3cf",
        "tertiary-container": "#5fefff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#474747",
        "on-tertiary-container": "#006b74",
        "surface-dim": "#dfdac7",
        "surface-container-lowest": "#ffffff",
        "background": "#fff9e6",
        "tertiary-fixed": "#8af2ff",
        "on-secondary-container": "#646464",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed-variant": "#004f56",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container": "#f3eeda",
        "inverse-on-surface": "#f6f1dd",
        "inverse-primary": "#d8ca00",
        "secondary": "#5e5e5e",
        "on-background": "#1d1c10",
        "on-surface-variant": "#4a4732",
        "on-tertiary-fixed": "#001f23",
        "surface-container-high": "#ede8d5",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#333124",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container-low": "#f9f4e0",
        "surface-tint": "#676000",
        "on-primary-fixed-variant": "#4e4800",
        "on-surface": "#1d1c10",
        "secondary-fixed-dim": "#c8c6c6",
        "tertiary": "#006972",
        "secondary-fixed": "#e4e2e2",
        "outline-variant": "#ccc7ab",
        "outline": "#7b785f",
        "surface-container-highest": "#e8e3cf",
        "primary-container": "#efdf00",
        "primary-fixed-dim": "#d8ca00",
        "on-primary-fixed": "#1f1c00",
        "primary": "#676000",
        "surface-bright": "#fff9e6",
        "tertiary-fixed-dim": "#42d9e9",
        "secondary-container": "#e4e2e2",
        "primary-fixed": "#f6e614",
        // Keeping compatibility colors for existing components during transition
        "renault-yellow": "#EFDF00",
        "renault-blue": "#1883FD",
        "absolute-black": "#000000",
        "pure-white": "#FFFFFF",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "stack-md": "24px",
        "margin-desktop": "40px",
        "unit": "4px",
        "stack-lg": "48px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "stack-sm": "8px"
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        "headline-md": ["var(--font-space-grotesk)"],
        "label-caps": ["var(--font-space-grotesk)"],
        "display-lg": ["var(--font-space-grotesk)"],
        "title-sm": ["var(--font-space-grotesk)"],
        "body-md": ["var(--font-space-grotesk)"],
        "space-grotesk": ["var(--font-space-grotesk)"]
      },
      fontSize: {
        "headline-md": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "title-sm": ["20px", { "lineHeight": "1.4", "letterSpacing": "0em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "letterSpacing": "0em", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
};
