FROM node:22-slim

WORKDIR /app

COPY package*.json ./

RUN npm install --omit=dev && \
    npm install -g pm2 && \
    npm cache clean --force

COPY . .

RUN groupadd -g 1001 nodejs && \
    useradd -r -u 1001 -g nodejs nodejs && \
    chown -R nodejs:nodejs /app

USER nodejs

CMD ["npm", "run", "worker"]
